### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by cfytrok** [TinkeringCode/PokerRL#15]
Great project, but hard to figure out the code.
Could you please add some more examples and documentation.
Examples from this repository do not match the documentation. Where are Driver and Evaluator? The examples from the DeepCFR project are too complicated.
How to use each component of framework?
How can they be used in interactive mode?

**Comment by EricSteinberger** [comment]
The code is well documented and released for free. Where do examples not match the docs? Many people managed to figure it out and use the repository and at least one research team based a paper on it. Show some gratitude man, this is 100s of hours of work released for free. I'm not helping you this way.
