### ISSUE TITLE
Hand Eval for Mac OS

### ISSUE THREAD

**Issue by SavvaI** [TinkeringCode/PokerRL#2]
Could you please compile hand evaluation for mac os?

**Comment by pouhasoizgasdohu** [comment]
I thought .so would work on all Unix systems. I do not have a computer running mac os myself, so I, unfortunately, can't help.

You could set up a VM or a Docker container on your machine instead. That should work regardless of which OS you use personally.

**Comment by TinkeringCode** [comment]
I thought .so would work on all Unix systems. I do not have a computer running mac os myself, so I can't test it.

You could set up a VM or a Docker container on your machine instead. This should work regardless of which OS you use personally.
