### ISSUE TITLE
EvalAgentBase class errors

### ISSUE THREAD

**Issue by m0n0l0c0** [TinkeringCode/PokerRL#4]
Hi @TinkeringCode,

First of all, great work you have here! Really useful.

I am trying to replicate some of your experiments (play against DeepCFR for example), but I am getting two errors.

Trying to play interactively against the algorithm (modified `examples/interactive_v_agent.py`), when human plays first, the `notify_of_processed_tuple_action` method gets executed ([line 103](https://github.com/TinkeringCode/PokerRL/blob/8ad215483c252b427b3283e08c18815638a65212/PokerRL/game/InteractiveGame.py#L103)) and errors with: `TypeError: notify_of_processed_tuple_action() got an unexpected keyword argument 'action_tuple'`. I think the arguments are reversed and misnamed in EvalAgentBase class, it seems pretty straight forward (I can submit a PR fixing it).

The second error comes when the algorithm plays, `get_action_frac_tuple` method gets called, but it does not exist in the base class `AttributeError: 'EvalAgentDeepCFR' object has no attribute 'get_action_frac_tuple'`. This seems more difficult to solve, I haven't studied the code in depth, I assume the action could be get from `get_action` overridden method, but it's not clear to me how to get the fraction or bet size.

MWE (inside the DeepCFR repo)

```python
from os.path import dirname, abspath

from DeepCFR.EvalAgentDeepCFR import EvalAgentDeepCFR
from PokerRL.game.InteractiveGame import InteractiveGame

path_to_sdcfr_eval_agent = dirname(abspath(__file__)) + "/trained_agents/Example_FHP_SINGLE.pkl"

if __name__ == '__main__':
    eval_agent = EvalAgentDeepCFR.load_from_disk(path_to_eval_agent=path_to_sdcfr_eval_agent)

    # to replicate error 1, when prompted choose any action
    plays_first = [0]
    # then, to replicate error 2, change 
    # plays_first = [1]
    # so that the algorithm starts and the second error is triggered
    game = InteractiveGame(env_cls=eval_agent.env_bldr.env_cls,
                           env_args=eval_agent.env_bldr.env_args,
                           seats_human_plays_list=plays_first,
                           eval_agent=eval_agent,
                           )

    game.start_to_play()
```

Kind Regards,
Guillermo.

**Comment by TinkeringCode** [comment]
Hi Guillermo,

Thank you!

Thanks for posting. I will try to reproduce and fix this over the weekend.

In the meantime, please provide tracebacks for both errors if possible. This would make it easier for me to try to understand why they happen on your machine.

Best wishes,
Eric

**Comment by m0n0l0c0** [comment]
Hello Eric,

Thanks for the fast reply!

Sure, here it goes, first error:
```
Traceback (most recent call last):
  File "interactive_v_agent.py", line 27, in <module>
    game.start_to_play()
  File "/home/gb/.local/share/virtualenvs/poker_rl-trFKka7d/lib/python3.6/site-packages/PokerRL/game/InteractiveGame.py", line 104, in start_to_play
    p_id_acted=current_player_id)
TypeError: notify_of_processed_tuple_action() got an unexpected keyword argument 'action_tuple'
```

and the second error:
```bash
Traceback (most recent call last):
  File "interactive_v_agent.py", line 27, in <module>
    game.start_to_play()
  File "/home/gb/.local/share/virtualenvs/poker_rl-trFKka7d/lib/python3.6/site-packages/PokerRL/game/InteractiveGame.py", line 108, in start_to_play
    a_idx, frac = self._eval_agent.get_action_frac_tuple(step_env=True)
AttributeError: 'EvalAgentDeepCFR' object has no attribute 'get_action_frac_tuple'
```
I'm working inside a virtualenv

Best,
Guillermo.

**Comment by TinkeringCode** [comment]
Hi!

I believe I have fixed it. Please pull the master of Deep CFR (also needed to make changes there, but the old .pkl agents are still compatible). Moreover, please pull the PokerRL master into the same project on your machine and uninstall the pip version. If this works, I will upload the new PokerRL with the fix to pip.

Best
Eric

**Comment by m0n0l0c0** [comment]
Hello!

Nice, thanks for the quick fix! I'll take a look as soon as possible and log it back here.

Best,
Guillermo

**Comment by m0n0l0c0** [comment]
Hello Eric,

I've tested it and works perfectly fine! :)
Also, I have submitted a pull request with some things that seemed to be left behind.

Cheers,
Guillermo.

**Comment by TinkeringCode** [comment]
Hi Guillermo,

Thanks for testing! Great to hear that it works now. :)
I merged your PR - thanks for cleaning up.

pip version is going to be updated this week!

Cheers,
Eric

**Comment by franz101** [comment]
Interactive Playing does not work here. Player two always wins no matter the action of Player one. Maybe I did not get something will check tommorrow and reproduce the error. Any way great work! Great for research.

**Comment by franz101** [comment]
Problem solved, seems it was related to pip :)
